# File: monitoring/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the gesture recognition API
  - job_name: 'gesture-api'
    static_configs:
      - targets: ['gesture-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Scrape system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']